## Step 0: Import libraries

In [1]:
import io
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None, "display.width", 200)

## Step 1: Create a synthetic dataset
This stands in for a real CSV/JSON file. It is written to in-memory 'files' so we can use the real `read_csv()` / `read_json()` functions.

In [2]:
rng = np.random.default_rng(42)
n = 200
raw = pd.DataFrame({
    "Order ID": np.arange(1001, 1001 + n),
    "Customer Name": [f"Customer_{i:03d}" for i in rng.integers(1, 60, n)],
    "City": rng.choice(["Surat", "Ahmedabad", "Mumbai", "Pune", "Vadodara", "Rajkot"], n),
    "Product Category": rng.choice(["Electronics", "Clothing", "Groceries", "Furniture", "Books"], n),
    "Quantity": rng.integers(1, 10, n),
    "Unit Price": np.round(rng.uniform(100, 5000, n), 2),
    "Discount %": rng.choice([0, 5, 10, 15, 20], n),
    "Order Date": pd.date_range("2025-01-01", periods=n, freq="D").strftime("%Y-%m-%d"),
})

csv_file = io.StringIO()
raw.to_csv(csv_file, index=False)
csv_file.seek(0)
json_file = io.StringIO(raw.to_json(orient="records"))

## Step 2: Load the dataset (CSV)

In [3]:
df = pd.read_csv(csv_file)
print("Dataset loaded successfully!")

Dataset loaded successfully!

## Step 3: First 5 rows – `head()`

In [4]:
df.head()

   Order ID Customer Name      City Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001  Customer_006    Mumbai            Books         6     1579.44          20  2025-01-01
1      1002  Customer_046    Rajkot        Furniture         8     4600.37          10  2025-01-02
2      1003  Customer_039    Mumbai         Clothing         7     3928.34          20  2025-01-03
3      1004  Customer_026  Vadodara            Books         2      641.88          15  2025-01-04
4      1005  Customer_026    Mumbai        Groceries         8     4985.47          15  2025-01-05

## Step 4: Last 5 rows – `tail()`

In [5]:
df.tail()

     Order ID Customer Name       City Product Category  Quantity  Unit Price  Discount %  Order Date
195      1196  Customer_006     Rajkot            Books         3     1462.31          10  2025-07-15
196      1197  Customer_021      Surat        Groceries         9     3544.86          15  2025-07-16
197      1198  Customer_007  Ahmedabad        Furniture         5     3205.47          15  2025-07-17
198      1199  Customer_020  Ahmedabad        Furniture         3     4910.85           0  2025-07-18
199      1200  Customer_057  Ahmedabad        Furniture         4     3139.75           5  2025-07-19

## Step 5: Dimensions (shape) and column names

In [6]:
print("Shape (rows, columns):", df.shape)
print("Column names:", df.columns.tolist())

Shape (rows, columns): (200, 8)
Column names: ['Order ID', 'Customer Name', 'City', 'Product Category', 'Quantity', 'Unit Price', 'Discount %', 'Order Date']

## Step 6: Data types and non-null counts – `info()`

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          200 non-null    int64
 1   Customer Name     200 non-null    str
 2   City              200 non-null    str
 3   Product Category  200 non-null    str
 4   Quantity          200 non-null    int64
 5   Unit Price        200 non-null    float64
 6   Discount %        200 non-null    int64
 7   Order Date        200 non-null    str
dtypes: float64(1), int64(3), str(4)
memory usage: 12.6 KB

## Step 7: Summary statistics – `describe(include='all')`
Numeric columns show mean/std/quartiles; categorical columns show count/unique/top/freq.

In [8]:
df.describe(include='all')

           Order ID Customer Name       City Product Category    Quantity   Unit Price  Discount %  Order Date
count    200.000000           200        200              200  200.000000   200.000000  200.000000         200
unique          NaN            55          6                5         NaN          NaN         NaN         200
top             NaN  Customer_006  Ahmedabad            Books         NaN          NaN         NaN  2025-01-01
freq            NaN             8         41               51         NaN          NaN         NaN           1
mean    1100.500000           NaN        NaN              NaN    5.245000  2524.847600   10.825000         NaN
std       57.879185           NaN        NaN              NaN    2.501251  1432.267879    6.977665         NaN
min     1001.000000           NaN        NaN              NaN    1.000000   126.610000    0.000000         NaN
25%     1050.750000           NaN        NaN              NaN    3.000000  1232.087500    5.000000         NaN
50%     1100.500000           NaN        NaN              NaN    5.000000  2572.840000   10.000000         NaN
75%     1150.250000           NaN        NaN              NaN    7.000000  3742.247500   15.000000         NaN
max     1200.000000           NaN        NaN              NaN    9.000000  4995.610000   20.000000         NaN

## Step 8: Load the same data from JSON

In [9]:
df_json = pd.read_json(json_file)
print("JSON load – shape:", df_json.shape)
df_json.head()

JSON load – shape: (200, 8)

   Order ID Customer Name      City Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001  Customer_006    Mumbai            Books         6     1579.44          20  2025-01-01
1      1002  Customer_046    Rajkot        Furniture         8     4600.37          10  2025-01-02
2      1003  Customer_039    Mumbai         Clothing         7     3928.34          20  2025-01-03
3      1004  Customer_026  Vadodara            Books         2      641.88          15  2025-01-04
4      1005  Customer_026    Mumbai        Groceries         8     4985.47          15  2025-01-05